import AuthContext from '@/context/AuthContext';
import './globals.css';
import { inter } from '@/util/font';



// const inter = Noto_Sans_KR({ weight: '500', subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
type props = {
  children: React.ReactNode;
};
export default async function RootLayout({ children }: props) {

  return (
    <html lang="kr">
      <body className={inter.className} >
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
